# Generated by Django 4.2.3 on 2023-08-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pal',
            name='age',
            field=models.IntegerField(max_length=3),
        ),
    ]
